### ISSUE TITLE
Error message while using the command "ctmlc"

### ISSUE THREAD

**Issue by postpostscript** [weaversam8/ctml#1]
I used the command `ctmlc testing.ctml`, and got an error:

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1001:11)
    at Process.ChildProcess._handle.onexit (child_process.js:792:34)
```

The content of `testing.html` is

```
-html
    -head
        -title
            Title!
        -
        -script [src="test.js"]
        -
    -
    -body
        This is some text
    -
-
```

**Comment by weaversam8** [comment]
Your code syntax looks good, make sure you're updated to the latest version, 0.3.4 as of right now. Additionally, you said that was the contents of `index.html` while you executed the command on `index.ctml`.

**Comment by postpostscript** [comment]
I meant to say `testing.ctml` both times.

**Comment by postpostscript** [comment]
I am on version `0.3.4`. I used the `npm install -g ctml` command to install.

**Comment by weaversam8** [comment]
Try running the software with no arguments. Does it print usage information?

**Comment by postpostscript** [comment]
It does.

**Comment by weaversam8** [comment]
Try executing it with the `--file` option. Additionally, try passing .\filename

**Comment by postpostscript** [comment]
All of these had the same error:
`ctmlc --file 'testing.ctml'`
`ctmlc --file testing.ctml`
`ctmlc --file ./testing.ctml`
`ctmlc ./testing.ctml`
`ctmlc testing.ctml`

**Comment by weaversam8** [comment]
Run `npm link` in the directory that CTML was installed in. See if that works for a temporary fix.

**Comment by postpostscript** [comment]
When I ran `npm link` I got the error messages:

```
$ npm link
npm ERR! Error: ENOENT, stat '/usr/lib/node_modules/ctml'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.14.27-25.47.amzn1.x86_64
npm ERR! command "node" "/usr/bin/npm" "link"
npm ERR! cwd /usr/lib/node_modules/ctml
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.3.6
npm ERR! path /usr/lib/node_modules/ctml
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! Error: ENOENT, open 'npm-debug.log'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.14.27-25.47.amzn1.x86_64
npm ERR! command "node" "/usr/bin/npm" "link"
npm ERR! cwd /usr/lib/node_modules/ctml
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.3.6
npm ERR! path npm-debug.log
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /usr/lib/node_modules/ctml/npm-debug.log
npm ERR! not ok code 0
```

**Comment by weaversam8** [comment]
Run it in the directory in which it was installed by NPM global. This should be in your appdata directory.

**Comment by weaversam8** [comment]
Try running all of the suggested commands with sudo. The `npm install -g ctml` should be sudo as well.
EDIT: If it wasn't globally installed with sudo, you'll need to uninstall it and reinstall.
